name: ElytraPlus
version: '${project.version}'
main: cn.ericcraft.elytraPlus.ElytraPlus
api-version: '1.13'
author: Eric
description: A plugin that allows players to fly with elytra.
website: https://github.com/Flock-YT/ElytraPlus
commands:
  fly:
    description: Enables creative flight mode while wearing elytra.
    usage: /fly
permissions:
  elytraplus.use:
    description: 允许使用 /fly 指令开启鞘翅飞行模式
    default: op
  elytraplus.bypass.durability:
    description: 允许玩家在本插件飞行时不消耗耐久
    default: false
  elytraplus.bypass.world:
    description: 允许玩家忽略世界白名单或黑名单限制
    default: op
